### ISSUE TITLE
Package setup

### ISSUE THREAD

**Issue by SteGriff** [onlyskin/kanjiapi.dev#11]
Hi! Thank you for making this project.

I recently set it up on Windows (and I'm not a Python developer) and I found that I had to `pip install` a few other packages, notably `ujson` and `lxml`.

I noticed the only thing in `requirements.txt` is PyTest. 

I am happy to do a PR if you can advise me that I'm not barking up the wrong tree with this... 😄 

Thanks again,
Ste

**Comment by onlyskin** [comment]
Hey, yep you're right they should be in the `requirements.txt`

Feel free to PR 🙂

**Comment by onlyskin** [comment]
Just fixed this in https://github.com/onlyskin/kanjiapi.dev/commit/31e6f4bd850951e5c1e2f0431467e4b9d075f8af
