### ISSUE TITLE
New project using the kanjiapi

### ISSUE THREAD

**Issue by dpars34** [onlyskin/kanjiapi.dev#20]
Hi there,

Thank you for your work with the API, it's exactly what I was looking for. I've made a website which uses your API and if you're interested I would be very grateful if you could mention it on the website. You can find my website at: https://www.onkun.org.

Thanks for again for the brilliant API!

**Comment by onlyskin** [comment]
Hi, thanks for your message, I'd be happy to link to your website from kanjiapi.dev!

What would you like as the tagline?
For example, I could put something such as "onkun: the simple kanji dictionary"

**Comment by dpars34** [comment]
That tagline would be perfect!

Thanks again, I appreciate it a lot, and keep up the good work!

**Comment by onlyskin** [comment]
No problem! This is now live at https://kanjiapi.dev/
