### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FadliDarmawan** [onlyskin/kanjiapi.dev#21]
![Screenshot_20210529-231722_WhatsAppBusiness.jpg](https://user-images.githubusercontent.com/79369935/120077316-1c941a80-c0d4-11eb-831f-72e55c3beaef.jpg)

![Screenshot_20210529-231733_Acode.jpg](https://user-images.githubusercontent.com/79369935/120077322-1f8f0b00-c0d4-11eb-8ca9-751b9adb3e2a.jpg)

Can you fix this?

**Comment by onlyskin** [comment]
Hi, you are received a 404 page because you are requesting the URL `https://kanjiapi.dev/v1/kanji` – this is a 404 as it is not an endpoint supported by the API.

If you would like to get a list of all kanji, please see the API documentation here for further information: https://kanjiapi.dev/#!/documentation. There are various endpoints for different sets of kanji, but note that they return lists of strings of kanji, not nested data. For that you will need to make a second API request.

I hope this helps.

**Comment by FadliDarmawan** [comment]
> Hi, you are received a 404 page because you are requesting the URL `https://kanjiapi.dev/v1/kanji` – this is a 404 as it is not an endpoint supported by the API.
> 
> If you would like to get a list of all kanji, please see the API documentation here for further information: https://kanjiapi.dev/#!/documentation. There are various endpoints for different sets of kanji, but note that they return lists of strings of kanji, not nested data. For that you will need to make a second API request.
> 
> I hope this helps.

If i want to make Kanji Search Feature what should i do?

**Comment by onlyskin** [comment]
It depends what you mean by 'Kanji Search'.

If you want to look up details for a kanji, you can do this with the endpoint: `https://kanjiapi.dev/v1/kanji/{character}`, substituting `{character}` with the kanji you want to look up, for example: `https://kanjiapi.dev/v1/kanji/猫` will return json information about the kanji "猫".

You could do this in JavaScript like so:
```js
> fetch('https://kanjiapi.dev/v1/kanji/猫').then(r => r.json()).then(console.log);
{
  "kanji": "猫",
  "grade": 8,
  "stroke_count": 11,
  "meanings": [
    "cat"
  ],
  "kun_readings": [
    "ねこ"
  ],
  "on_readings": [
    "ビョウ"
  ],
  "name_readings": [],
  "jlpt": 2,
  "unicode": "732b"
}
```

**Comment by FadliDarmawan** [comment]
> It depends what you mean by 'Kanji Search'.
> 
> If you want to look up details for a kanji, you can do this with the endpoint: `https://kanjiapi.dev/v1/kanji/{character}`, substituting `{character}` with the kanji you want to look up, for example: `https://kanjiapi.dev/v1/kanji/猫` will return json information about the kanji "猫".
> 
> You could do this in JavaScript like so:
> ```js
> > fetch('https://kanjiapi.dev/v1/kanji/猫').then(r => r.json()).then(console.log);
> {
>   "kanji": "猫",
>   "grade": 8,
>   "stroke_count": 11,
>   "meanings": [
>     "cat"
>   ],
>   "kun_readings": [
>     "ねこ"
>   ],
>   "on_readings": [
>     "ビョウ"
>   ],
>   "name_readings": [],
>   "jlpt": 2,
>   "unicode": "732b"
> }
> ```

Thx, now it's work

**Comment by onlyskin** [comment]
Great :)
