### ISSUE TITLE
grade7

### ISSUE THREAD

**Issue by sinzhin** [onlyskin/kanjiapi.dev#4]
api for https://kanjiapi.dev/v1/kanji/grade-7 isnt working.
its working for 1 thru 6 and 8 though

**Comment by onlyskin** [comment]
This is a (lack of) documentation issue, I have updated https://github.com/onlyskin/kanjiapi.dev/issues/3 to cover this, thanks for flagging it up!

The kanji grade levels:
1-6 indicates a Kyōiku kanji of the specified grade
8 indicates a Jōyō kanji of junior high school grade
9/10 indicate Jinmeiyō

(See http://www.edrdg.org/kanjidic/kanjidic2_dtdh.html)
