### ISSUE TITLE
Incorrect JLPT for Kanji

### ISSUE THREAD

**Issue by john-crossley** [onlyskin/kanjiapi.dev#5]
Hey,

I've just finished setting this up and the first endpoint I tried to hit seemed to have incorrect data for **今**

I tried to hit the endpoint for `https://kanjiapi.dev/v1/kanji/今` and the response I got showed 今 as being part of JLPT 4 when in fact it seems to be JLPT 5. Perhaps I'm missing something.

I tried to download the latest `JMdict` and `kanjidic2.xml` so maybe this data is out of date?

Ta ✌️

**Comment by onlyskin** [comment]
Hey,

It seems 今 is listed as JLPT 4 in the kanjidic2 (see line `62227` in the latest `kanjidic2.xml`).

The DTD for kanjidic2 (http://www.edrdg.org/kanjidic/kanjidic2_dtdh.html) gives the following information for the jlpt grading:
```<!ELEMENT jlpt (#PCDATA)>
	<!--
	The (former) Japanese Language Proficiency test level for this kanji. 
	Values range from 1 (most advanced) to 4 (most elementary). This field 
	does not appear for kanji that were not required for any JLPT level.
	Note that the JLPT test levels changed in 2010, with a new 5-level
	system (N1 to N5) being introduced. No official kanji lists are
	available for the new levels. The new levels are regarded as
	being similar to the old levels except that the old level 2 is
	now divided between N2 and N3.
	-->```

**Comment by john-crossley** [comment]
Well that clears that up 🤣 thank you for taking time to respond. Also really appreciate this bit of software, good work! 👌🏻
