### ISSUE TITLE
"/words" endpoint - readings

### ISSUE THREAD

**Issue by davidb1** [onlyskin/kanjiapi.dev#7]
Is there a way to get a breakdown of the kanji's reading on the `words` api? (basically furigana)
Would this require additional calls to the `kanji` endpoints / Is this part of the dictionary?

For example, something like this:
```
{
    "variants": [
            {
                 "written": "日本語",
                 "pronounced": "にほんご",
                 "furigana/breakdown": [ "に", "ほん", "ご"]
```

**Comment by onlyskin** [comment]
Hi, you would need to make additional calls to the `/kanji` endpoint to determine the breakdown. This information isn't included in the source dictionary from which the `/words` endpoint is generated. It's not always obvious how to assign which part of the pronunciation to which kanji in a compound.
