### ISSUE TITLE
Getting a random kanji endpoint

### ISSUE THREAD

**Issue by cAstraea** [onlyskin/kanjiapi.dev#9]
Yahallo
Is there an endpoint for this ? I noticed on https://kai.kanjiapi.dev/#!/%E5%AD%97 has a I'm feeling lucky button but not sure it's generated by the API.

**Comment by onlyskin** [comment]
Hi,

No there isn't an endpoint to get a random kanji. There are endpoints to get various lists of kanji `https://kanjiapi.dev/v1/kanji/joyo`, `https://kanjiapi.dev/v1/kanji/jinmeiyo`, `https://kanjiapi.dev/v1/kanji/grade-1`, `https://kanjiapi.dev/v1/kanji/all`.

The kanjikai I'm feeling lucky button uses the `/kanji/joyo` and `/kanji/jinmeiyo` endpoints to get a list of kanji and then picks one randomly from those lists.
